### ISSUE TITLE
What is the significance of `command: local`?

### ISSUE THREAD

**Issue by vulcan25** [sleeske/docker-multi-stage-example#2]
In the [compose file on the opt branch](https://github.com/sleeske/docker-multi-stage-example/blob/opt/docker-compose.yml#L14) the following is specified for the `django` service...

```
version: '3'
services:
  django:
    command: local
```

My understanding is `local` prints out environment variables, and is possibly related to the `env_file:` setting.

However in the Dockerfile the following is specified:
```
ENTRYPOINT [ "/entrypoint.sh" ]
```

When I run `docker-compose up` this runs the entrypoint script, so what is the significance of `command: local`?

[the docs](https://docs.docker.com/compose/compose-file/#command) also point out that `entrypoint:` can be specified in the compose file to overide the image's `ENTRYPOINT` **and** `CMD`, where-as `command:` overides just the `CMD` by my understanding.

In this case is `local` ever run? (as there's no `CMD` in the Dockerfile).  What is its purpose here, and is it related to loading variables from `.env`?

**Comment by vulcan25** [comment]
Solved this myself.

It's passed to the `entrypoint.sh` script:
```
if [ "$1" = 'local' ]; then
    python manage.py runserver 0:8000
fi
```

Similarly I can define something different for `command:` in the compose then process it, for example:

```
if [ "$1" = 'gunicorn' ]; then
    gunicorn --bind=0.0.0.0:5000 run:app
fi
```

Cool.

**Comment by sleeske** [comment]
Hey!

Sorry for late reply, glad you've figured it out ;)
Combination of `command` and entrypoint file is a neat trick that keeps docker-compose file clean and allows execution of service-specific or shared init code. Kind of like beforeEach/beforeAll in tests ;)

**Comment by vulcan25** [comment]
Thanks.  Really neat tutorial by the way.  Perhaps you should have a link back to the tutorial from the README here.
